[package]
name = "eightbit-emu-app"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
cpal = "0.15.3"
muda = { version = "0.21.0", default-features = false }
pollster = "1.0.1"
rfd = "0.17.2"
eightbit-emu-core = { path = "../eightbit-emu-core" }
wgpu = { version = "30.0.1", features = ["wgsl"] }
winit = "0.30.13"

[[bin]]
name = "eightbit-emu"
path = "src/main.rs"
