use winit::keyboard::KeyCode;

pub fn quits(_code: KeyCode) -> bool {
    false
}

pub fn kempston_bit(code: KeyCode) -> Option<u8> {
    match code {
        KeyCode::ArrowRight => Some(0x01),
        KeyCode::ArrowLeft => Some(0x02),
        KeyCode::ArrowDown => Some(0x04),
        KeyCode::ArrowUp => Some(0x08),
        KeyCode::AltRight => Some(0x10),
        _ => None,
    }
}

pub fn spectrum_key(code: KeyCode) -> Option<(u8, u8)> {
    match code {
        KeyCode::ShiftLeft => Some((0, 0x01)),
        KeyCode::KeyZ => Some((0, 0x02)),
        KeyCode::KeyX => Some((0, 0x04)),
        KeyCode::KeyC => Some((0, 0x08)),
        KeyCode::KeyV => Some((0, 0x10)),
        KeyCode::KeyA => Some((1, 0x01)),
        KeyCode::KeyS => Some((1, 0x02)),
        KeyCode::KeyD => Some((1, 0x04)),
        KeyCode::KeyF => Some((1, 0x08)),
        KeyCode::KeyG => Some((1, 0x10)),
        KeyCode::KeyQ => Some((2, 0x01)),
        KeyCode::KeyW => Some((2, 0x02)),
        KeyCode::KeyE => Some((2, 0x04)),
        KeyCode::KeyR => Some((2, 0x08)),
        KeyCode::KeyT => Some((2, 0x10)),
        KeyCode::Digit1 => Some((3, 0x01)),
        KeyCode::Digit2 => Some((3, 0x02)),
        KeyCode::Digit3 => Some((3, 0x04)),
        KeyCode::Digit4 => Some((3, 0x08)),
        KeyCode::Digit5 => Some((3, 0x10)),
        KeyCode::Digit0 => Some((4, 0x01)),
        KeyCode::Digit9 => Some((4, 0x02)),
        KeyCode::Digit8 => Some((4, 0x04)),
        KeyCode::Digit7 => Some((4, 0x08)),
        KeyCode::Digit6 => Some((4, 0x10)),
        KeyCode::KeyP => Some((5, 0x01)),
        KeyCode::KeyO => Some((5, 0x02)),
        KeyCode::KeyI => Some((5, 0x04)),
        KeyCode::KeyU => Some((5, 0x08)),
        KeyCode::KeyY => Some((5, 0x10)),
        KeyCode::Enter => Some((6, 0x01)),
        KeyCode::KeyL => Some((6, 0x02)),
        KeyCode::KeyK => Some((6, 0x04)),
        KeyCode::KeyJ => Some((6, 0x08)),
        KeyCode::KeyH => Some((6, 0x10)),
        KeyCode::Space => Some((7, 0x01)),
        KeyCode::ShiftRight | KeyCode::ControlLeft => Some((7, 0x02)),
        KeyCode::KeyM => Some((7, 0x04)),
        KeyCode::KeyN => Some((7, 0x08)),
        KeyCode::KeyB => Some((7, 0x10)),
        _ => None,
    }
}

pub fn c64_key(code: KeyCode) -> Option<(u8, u8)> {
    match code {
        KeyCode::Backspace => Some((0, 0)),
        KeyCode::Enter => Some((1, 0)),
        KeyCode::ArrowRight | KeyCode::ArrowLeft => Some((2, 0)),
        KeyCode::ArrowDown | KeyCode::ArrowUp => Some((7, 0)),
        KeyCode::Digit3 => Some((0, 1)),
        KeyCode::KeyW => Some((1, 1)),
        KeyCode::KeyA => Some((2, 1)),
        KeyCode::Digit4 => Some((3, 1)),
        KeyCode::KeyZ => Some((4, 1)),
        KeyCode::KeyS => Some((5, 1)),
        KeyCode::KeyE => Some((6, 1)),
        KeyCode::ShiftLeft => Some((7, 1)),
        KeyCode::Digit5 => Some((0, 2)),
        KeyCode::KeyR => Some((1, 2)),
        KeyCode::KeyD => Some((2, 2)),
        KeyCode::Digit6 => Some((3, 2)),
        KeyCode::KeyC => Some((4, 2)),
        KeyCode::KeyF => Some((5, 2)),
        KeyCode::KeyT => Some((6, 2)),
        KeyCode::KeyX => Some((7, 2)),
        KeyCode::Digit7 => Some((0, 3)),
        KeyCode::KeyY => Some((1, 3)),
        KeyCode::KeyG => Some((2, 3)),
        KeyCode::Digit8 => Some((3, 3)),
        KeyCode::KeyB => Some((4, 3)),
        KeyCode::KeyH => Some((5, 3)),
        KeyCode::KeyU => Some((6, 3)),
        KeyCode::KeyV => Some((7, 3)),
        KeyCode::Digit9 => Some((0, 4)),
        KeyCode::KeyI => Some((1, 4)),
        KeyCode::KeyJ => Some((2, 4)),
        KeyCode::Digit0 => Some((3, 4)),
        KeyCode::KeyM => Some((4, 4)),
        KeyCode::KeyK => Some((5, 4)),
        KeyCode::KeyO => Some((6, 4)),
        KeyCode::KeyN => Some((7, 4)),
        KeyCode::KeyP => Some((1, 5)),
        KeyCode::KeyL => Some((2, 5)),
        KeyCode::Period => Some((4, 5)),
        KeyCode::Comma => Some((7, 5)),
        KeyCode::ShiftRight => Some((4, 6)),
        KeyCode::Slash => Some((7, 6)),
        KeyCode::Digit1 => Some((0, 7)),
        KeyCode::ControlLeft => Some((2, 7)),
        KeyCode::Digit2 => Some((3, 7)),
        KeyCode::Space => Some((4, 7)),
        KeyCode::AltLeft => Some((5, 7)),
        KeyCode::KeyQ => Some((6, 7)),
        KeyCode::Escape => Some((7, 7)),
        _ => None,
    }
}
