use winit::keyboard::KeyCode;

pub fn spectrum_key(code: KeyCode) -> Option<(u8, u8)> {
    match code {
        KeyCode::ShiftLeft => Some((0, 0x01)),
        KeyCode::KeyZ => Some((0, 0x02)),
        KeyCode::KeyX => Some((0, 0x04)),
        KeyCode::KeyC => Some((0, 0x08)),
        KeyCode::KeyV => Some((0, 0x10)),
        KeyCode::KeyA => Some((1, 0x01)),
        KeyCode::KeyS => Some((1, 0x02)),
        KeyCode::KeyD => Some((1, 0x04)),
        KeyCode::KeyF => Some((1, 0x08)),
        KeyCode::KeyG => Some((1, 0x10)),
        KeyCode::KeyQ => Some((2, 0x01)),
        KeyCode::KeyW => Some((2, 0x02)),
        KeyCode::KeyE => Some((2, 0x04)),
        KeyCode::KeyR => Some((2, 0x08)),
        KeyCode::KeyT => Some((2, 0x10)),
        KeyCode::Digit1 => Some((3, 0x01)),
        KeyCode::Digit2 => Some((3, 0x02)),
        KeyCode::Digit3 => Some((3, 0x04)),
        KeyCode::Digit4 => Some((3, 0x08)),
        KeyCode::Digit5 => Some((3, 0x10)),
        KeyCode::Digit0 => Some((4, 0x01)),
        KeyCode::Digit9 => Some((4, 0x02)),
        KeyCode::Digit8 => Some((4, 0x04)),
        KeyCode::Digit7 => Some((4, 0x08)),
        KeyCode::Digit6 => Some((4, 0x10)),
        KeyCode::KeyP => Some((5, 0x01)),
        KeyCode::KeyO => Some((5, 0x02)),
        KeyCode::KeyI => Some((5, 0x04)),
        KeyCode::KeyU => Some((5, 0x08)),
        KeyCode::KeyY => Some((5, 0x10)),
        KeyCode::Enter => Some((6, 0x01)),
        KeyCode::KeyL => Some((6, 0x02)),
        KeyCode::KeyK => Some((6, 0x04)),
        KeyCode::KeyJ => Some((6, 0x08)),
        KeyCode::KeyH => Some((6, 0x10)),
        KeyCode::Space => Some((7, 0x01)),
        KeyCode::ShiftRight | KeyCode::ControlLeft => Some((7, 0x02)),
        KeyCode::KeyM => Some((7, 0x04)),
        KeyCode::KeyN => Some((7, 0x08)),
        KeyCode::KeyB => Some((7, 0x10)),
        _ => None,
    }
}
